FROM ubuntu:16.04

VOLUME ["/opt/"]

WORKDIR /root

ADD build.sh build.sh

RUN chmod a+x ~/build.sh && \
  apt update && \
  apt install -y git default-jdk maven && \
  git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello

CMD ["/root/build.sh"]