FROM ubuntu:16.04

EXPOSE 8080/tcp
VOLUME ["/opt/"]

RUN apt update && \
  apt install -y default-jdk tomcat8 && \
  mv /opt/hello-1.0.war /var/lib/tomcat8/webapps/

ENV CATALINA_BASE /var/lib/tomcat8/

CMD ["/usr/share/tomcat8/bin/catalina.sh", "run"]