FROM ubuntu:16.04

EXPOSE 8080/tcp
VOLUME ["/opt/"]

ADD run.sh /root/run.sh

RUN apt update && \
  apt install -y default-jdk tomcat8 && \
  chmod a+x /root/run.sh

ENV CATALINA_BASE /var/lib/tomcat8/

CMD ["/root/run.sh"]